{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" .Values.redis.labels.app }}
  namespace: {{ .Values.environments.namespace }}
spec:
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}