apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-login-script
  namespace: default
data:
  ecr-login-refresh-script.sh: |
    #!/bin/bash

    ECR_SECRET_NAME=regcd
    ECR_REGISTRY=$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com

    # AWS ECR 로그인 정보 갱신
    mkdir .aws
    echo -e "[dvc]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" > .aws/credentials.txt
    ECR_LOGIN=$(aws ecr get-login-password --region $AWS_REGION)

    # Kubernetes Secret 업데이트
    kubectl delete secret regcd -n default
    kubectl create secret docker-registry $ECR_SECRET_NAME \
      --docker-server=${ECR_REGISTRY} \
      --docker-username=AWS \
      --docker-password=${ECR_LOGIN} \
      --dry-run=client -o yaml | kubectl apply -f -