apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-login-refresh
  namespace: station
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ecr-login-refresh
            image: gtsopour/awscli-kubectl
            command: ["/bin/sh", "-c"]
            args:
              - cp /home/user/ecr-login-refresh-script.sh /tmp && chmod +x /tmp/ecr-login-refresh-script.sh && sh /tmp/ecr-login-refresh-script.sh
            volumeMounts:
            - name: script-volume
              mountPath: /home/user
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION
            - name: AWS_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCOUNT
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: ecr-login-script
