apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: dioai-bolero
type: Opaque
data:
  # Fill in the base64 encoded values for the following keys instead of e30=
  AWS_ACCESS_KEY_ID: e30=
  AWS_SECRET_ACCESS_KEY: e30=
  AWS_ACCOUNT: e30=
  AWS_REGION: e30=
