apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mortalgpu.fullname" . }}-config
  labels:
    {{- include "mortalgpu.labels" . | nindent 4 }}
data:
  config.yaml: |
    accelerator: nvidia
    processesDiscoveryPeriod: {{ .Values.config.deviceManager.processesDiscoveryPeriod | int }}
    deviceCacheTTL: {{ .Values.config.deviceManager.deviceCacheTTL | int }}
    mgctlMount: {{ .Values.config.mgctl.hostMount.enabled }}
    mgctlMountHostPath: {{ .Values.config.mgctl.hostMount.hostPath }}
    mgctlMountContainerPath: {{ .Values.config.mgctl.hostMount.containerPath }}
    serverAddr: 0.0.0.0:{{ required ".Values.service.ports.grpc must be set" .Values.service.ports.grpc }}
    memoryEnforcer: {{ .Values.config.memoryEnforcer }}
    deviceSpecs: {{ .Values.config.deviceSpecs }}
    jwtSecret: {{ .Values.config.grpcSecurity.jwtSecret }}
    deviceToken: {{ .Values.config.grpcSecurity.deviceToken }}
    containerToken: {{ .Values.config.grpcSecurity.containerToken }}
    {{- with .Values.config.deviceSharing }}
    deviceSharing:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.config.allocator }}
    allocator:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.config.pluginMounts }}
    pluginMounts:
      {{- toYaml . | nindent 6 }}
    {{- end }}