apiVersion: v1
kind: Service
metadata:
  name: {{ include "mortalgpu.fullname" . }}
  labels:
    {{- include "mortalgpu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.exporter.enabled }}
    - port: {{ .Values.service.ports.exporter }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.ports.mgdpMetrics }}
      targetPort: mgdp-metrics
      protocol: TCP
      name: mgdp-metrics
    {{- end }}
  selector:
    {{- include "mortalgpu.selectorLabels" . | nindent 4 }}
