{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mortalgpu.fullname" . }}-exporter
  labels:
    {{- include "mortalgpu.labels" . | nindent 4 }}
    {{- if .Values.exporter.serviceMonitor.labels -}}
    {{ toYaml .Values.exporter.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mortalgpu.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: {{ .Values.exporter.serviceMonitor.interval | quote }}
    - port: "mgdp-metrics"
      path: "/metrics"
      interval: {{ .Values.exporter.serviceMonitor.interval | quote }}
{{- end -}}