## Kafka configuration for asynchronous endpoint communication
## /secure/async/<model-name> will be the endpoint for the model
##
kafka:
  enabled: true

  controller:
    controllerOnly: true
    resourcesPreset: "eks-small"

    pdb:
      create: true
      minAvailable: ""
      maxUnavailable: 1
    
    persistence:
      enabled: true
      storageClass: "efs-sc"

    logPersistence:
      enabled: false
      storageClass: "efs-sc"
  
  broker:
    replicaCount: 3
    resourcesPreset: "eks-medium"

    pdb:
      create: true
      minAvailable: ""
      maxUnavailable: 1

    persistence:
      enabled: true
      storageClass: "efs-sc"

    logPersistence:
      enabled: false
      storageClass: "efs-sc"

  metrics:
    jmx:
      enabled: true
      resourcesPreset: "eks-micro"
  
  provisioning:
    enabled: true
    topics: 
      - name: "inst-gen-request"
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 1048576
          flush.messages: 1000

      - name: "inst-theme-group-request"
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 1048576
          flush.messages: 1000

      - name: "vocal-gen-request"
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 1048576
          flush.messages: 1000

      - name: "vocal-theme-group-request"
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 1048576
          flush.messages: 1000

      - name: "modulation-gen-request"
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 1048576
          flush.messages: 1000

      - name: "sustain-gen-request"
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 1048576
          flush.messages: 1000

kafka-ui:
  enabled: true

  yamlApplicationConfig:
    kafka:
      clusters:
        - name: kafka-cluster
          bootstrapServers: station-msa-api-kafka-broker-headless.station.svc.cluster.local:9092
          properties:
            security.protocol: PLAINTEXT

## Redis configuration for caching completed samples
## this will be used by the station service to return the generated samples
##
redis:
  enabled: true

  persistence:
    storageClass: "gp3"
    accessMode: "ReadWriteOnce"
    size: "10Gi"

  config:
    maxmemory: "256mb"
    maxmemoryPolicy: "allkeys-lru"
    requirepass: "jlk3s14vn"

  labels:
    app: redis
  
  service:
    type: ClusterIP
    port: 6379
  
  deployment:
    replicas: 1
    containerResources: {}


## Common annotations to scrape metrics of pods
##
prometheus:
  scrape: "true"
  port: "8080"
  path: "/metrics"

## Environment variables for the application
## clusterPlatform: "eks" or "onpremise"
## operation: "production" or "staging"
##
environments: 
  clusterPlatform: "eks"
  operation: "production"
  namespace: "station"

## Persistent volume claim for the application
## The models will be shared between station and each model service
##
persistence:
  accessMode: "ReadWriteMany"
  size: "25Gi"
  storageClass: "efs-sc"

station:
  labels:
    app: station

  deployment:
    stationContainer:
      image: <accound-id>.dkr.ecr.ap-northeast-2.amazonaws.com/station:<tag>
    sidecarContainer:
      image: <accound-id>.dkr.ecr.ap-northeast-2.amazonaws.com/ckpt_downloader:<tag>
    replicas: 1

  service:
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30100

models:
  instGen:
    deployment:
      deploymentName: inst-gen-deployment
      containerName: inst-gen-container
      labels:
        app: inst-gen
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      replicas: 6
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: inst-gen-svc
      serviceType: ClusterIP
      port: 8080

  instThemeGroup:
    deployment:
      deploymentName: inst-theme-group-deployment
      containerName: inst-theme-group-container
      labels:
        app: inst-theme-group
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "2"
      replicas: 2
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: inst-theme-group-svc
      serviceType: ClusterIP
      port: 8080

  lyricGen:
    deployment:
      deploymentName: lyric-gen-deployment
      containerName: lyric-gen-container
      labels:
        app: lyric-gen
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "3"
      replicas: 1
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: lyric-gen-svc
      serviceType: ClusterIP
      port: 8080  

  modulationGen:
    deployment:
      deploymentName: modulation-gen-deployment
      containerName: modulation-gen-container
      labels:
        app: modulation-gen
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "4"
      replicas: 1
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: modulation-gen-svc
      serviceType: ClusterIP
      port: 8080

  referenceAnalyze:
    deployment:
      deploymentName: reference-analyze-deployment
      containerName: reference-analyze-container
      labels:
        app: reference-analyze
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "5"
      replicas: 1
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: reference-analyze-svc
      serviceType: ClusterIP
      port: 8080

  sustainGen:
    deployment:
      deploymentName: sustain-gen-deployment
      containerName: sustain-gen-container
      labels:
        app: sustain-gen
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "6"
      replicas: 2
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: sustain-gen-svc
      serviceType: ClusterIP
      port: 8080

  vocalGen:
    deployment:
      deploymentName: vocal-gen-deployment
      containerName: vocal-gen-container
      labels:
        app: vocal-gen
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "7"
      replicas: 6
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: vocal-gen-svc
      serviceType: ClusterIP
      port: 8080

  vocalThemeGroup:
    deployment:
      deploymentName: vocal-theme-group-deployment
      containerName: vocal-theme-group-container
      labels:
        app: vocal-theme-group
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "8"
      replicas: 1
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: vocal-theme-group-svc
      serviceType: ClusterIP
      port: 8080

  refToMeta:
    deployment:
      deploymentName: reference-to-meta-deployment
      containerName: reference-to-meta-container
      labels:
        app: reference-to-meta
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        argocd.argoproj.io/sync-wave: "9"
      replicas: 0
      containerResources:
        limits:
          nvidia.com/gpu: 1
      affinities:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - g4dn.xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    service:
      name: reference-to-meta-svc
      serviceType: ClusterIP
      port: "8080"

