apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.station.labels.app }}
  namespace: {{ .Values.environments.namespace }}
  {{- with .Values.station.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.station.service.type }}
  {{- with .Values.station.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.station.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
